Recommend returning the same value/type from each call to `New()`.
dogmatiq/dogma pull request #123
Opened 2020-10-16 03:46 UTC by jmalloc

Fixes #79 

I didn't want to overspecify this, as it's likely we will need to allow for an aggregate to change the type used to represent it over time. For now I've simply recommended that the same type is always returned on repeat calls to `New()`.

2020-10-16 03:49 UTC, danilvpetrov approved these changes

2020-10-16 04:10 UTC, koden-km submitted a review, later dismissed

2020-10-17 01:09 UTC, jmalloc commented
Even though this is approved, after talking to Kev on slack I think these docs need further improvement.

2020-10-17 09:17 UTC, danilvpetrov requested changes

2020-10-17 09:17 UTC, danilvpetrov commented on aggregate.go
> +	// New constructs constructs new aggregate instance initialized with any
```suggestion
	// New constructs a new aggregate instance initialized with any
```

2020-10-17 09:17 UTC, danilvpetrov commented on process.go
> +	// New constructs constructs new process instance initialized with any
```suggestion
	// New constructs a new process instance initialized with any
```

2020-10-17 09:17 UTC, danilvpetrov commented on process.go
> +	// New constructs a new process instance and returns its root.
```suggestion
```

2020-10-17 23:37 UTC, jmalloc commented on aggregate.go
> +	// New constructs constructs new aggregate instance initialized with any
>_<

2020-10-18 23:34 UTC, koden-km approved these changes

2020-10-18 23:36 UTC, danilvpetrov approved these changes

2020-10-18 23:44 UTC, merged